### ISSUE TITLE
Expose tags in public API

### ISSUE THREAD

**Issue by codonnell** [clickingbuttons/arrow-zig#1]
I really appreciate all the work that's gone into this library! I've pulled the library in as a dependency using `build.zig.zon`, and I'm trying to run the sample as a sanity check. I copy pasted the sample file, but it seems like there isn't a way to access tags via the exposed public structs. Should they be exposed as public in `src/lib.zig`, or perhaps elsewhere? Or maybe I've misunderstood how the library is intended to be used, and they're supposed to be private. I can run the sample tests successfully if I call `arrow.sample.all` without attempting to import tags specifically.

**Comment by clickingbuttons** [comment]
> I'm trying to run the sample as a sanity check.

I've renamed `sample.zig` to `sample_arrays.zig`. It's really just sample arrays for internal library testing. The files in `examples` are what I meant to be run by users.

> it seems like there isn't a way to access tags via the exposed public structs.
Oops! The `Tag` struct is now available under `Array.Tag`.

**Comment by codonnell** [comment]
Thank you! Would it be possible to tag a new release? Whenever you have time--no rush.

**Comment by clickingbuttons** [comment]
Sorry it took a few days -- had to investigate a flatbuffers bug that was failing an integration test.

Should be good now in 0.0.4

**Comment by codonnell** [comment]
You have nothing to apologize for. I'm in no rush, and you are being kind enough to donate your time and expertise for free.

I don't actually see `0.0.4` on github. Is it possible you forgot to push up the tag?

**Comment by clickingbuttons** [comment]
I see it under https://github.com/clickingbuttons/arrow-zig/tags , but not the releases. Made one so it's more easily visible on github.

**Comment by codonnell** [comment]
I see it now, too. :+1: Thanks!
